# Updated Few-shot Prompt Template with examples
FEW_SHOT_PROMPT_TEMPLATE = """
                            You are a helpful assistant that answers questions based on the given context.

                            Here's an example of how to answer a question based on a context:

                            Context: The ship encountered an electrical failure on 01/01/2024 and the issue was resolved on 05/01/2024 by replacing the Magnetron.
                            Question: When did the defect occur?
                            Answer: The defect occurred on 01/01/2024.

                            Now, I'll provide you with a new context and question. Please answer the question based on the context provided.

                            Context: The repair of System 1 was successfully completed by Ram Vilas from Repair Unit 1.
                            Question: Who resolved the defect?
                            Answer: The defect was resolved by Ram Vilas from Repair Unit 1.

                            Now, here's your new context and question:

                            Context: {context}
                            Question: {query}

                            Answer based on the context:

                            The answer will be generated by the language model based on the context and the question. It might look something like this:

                            Answer: Based on the context, the defect was resolved by [name] from [repair unit].
                            """

CHAIN_OF_THOUGHT_PROMPT_TEMPLATE = """
                            You are a helpful assistant that answers questions based on the given context, using chain-of-thought reasoning to arrive at the answer.

                            Here's an example of how to answer a question based on a context, showing your reasoning:

                            Context: The ship encountered an electrical failure on 01/01/2024 and the issue was resolved on 05/01/2024 by replacing the Magnetron.
                            Question: When did the defect occur?
                            Answer:
                            Let's analyze the context step by step.
                            - The ship encountered an electrical failure on **01/01/2024**.
                            - The issue was resolved on 05/01/2024.
                            Therefore, the defect occurred on **01/01/2024**.

                            Now, I'll provide you with a new context and question. Please answer the question based on the context provided, showing your reasoning:

                            Context: The repair of System 1 was successfully completed by Ram Vilas from Repair Unit 1.
                            Question: Who resolved the defect?
                            Answer:
                            Let's break down the information given.
                            - The repair of System 1 was completed by **Ram Vilas**.
                            - He is from **Repair Unit 1**.
                            Therefore, the defect was resolved by **Ram Vilas from Repair Unit 1**.

                            Now, here's your new context and question:

                            Context: {context}
                            Question: {query}

                            Answer based on the context, showing your reasoning:

                            [Your answer should include a step-by-step explanation leading to the final answer.]
"""



prompt_template = """Based on the following context and query, provide a comprehensive response.

Example 1:

Context:
The city's public library will be closed next Monday for maintenance.

Query:
Is the public library open next Monday?

Response:
No, the city's public library will be closed next Monday due to maintenance.

Example 2:

Context:
A new species of bird has been discovered in the Amazon rainforest.

Query:
What recent discovery was made in the Amazon rainforest?

Response:
A new species of bird was discovered in the Amazon rainforest.

Now, based on the following context and query, provide a comprehensive response.

Context:
{context}

Query:
{query}

If there are images involved, consider their descriptions in the response.

Response:"""



image_description_prompt = """
    You are an assistant tasked with providing a detailed and comprehensive description of an image for retrieval.
    The summary should capture all visible aspects and details, including objects, colors, shapes, text, 
    background elements, and any other notable features. The description should be thorough to ensure that all 
    potential details are available for accurate retrieval.
    
    Image: {image}
    """